global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a-1:5000', 'service-a-2:5000', 'service-a-3:5000']

  - job_name: 'service-b'
    static_configs:
      - targets: ['game-service-1:5000', 'game-service-2:5000', 'game-service-3:5000']