# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tservice_a\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"Y\n\rScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x14\n\x0cgames_played\x18\x02 \x01(\x05\x12\x11\n\tgames_won\x18\x03 \x01(\x05\x12\x10\n\x08username\x18\x04 \x01(\t\"M\n\x12UpdateScoreRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x14\n\x0cscore_change\x18\x02 \x01(\x05\x12\x10\n\x08game_won\x18\x03 \x01(\x08\"2\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa0\x01\n\x0bUserService\x12\x42\n\x0cGetUserScore\x12\x16.service_a.UserRequest\x1a\x18.service_a.ScoreResponse\"\x00\x12M\n\x0fUpdateUserScore\x12\x1d.service_a.UpdateScoreRequest\x1a\x19.service_a.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=28
  _globals['_USERREQUEST']._serialized_end=58
  _globals['_SCORERESPONSE']._serialized_start=60
  _globals['_SCORERESPONSE']._serialized_end=149
  _globals['_UPDATESCOREREQUEST']._serialized_start=151
  _globals['_UPDATESCOREREQUEST']._serialized_end=228
  _globals['_UPDATERESPONSE']._serialized_start=230
  _globals['_UPDATERESPONSE']._serialized_end=280
  _globals['_USERSERVICE']._serialized_start=283
  _globals['_USERSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
